---
- name: Setup EC2 web server
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Install Apache and Git
      yum:
        name:
          - httpd
          - git
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: true

    - name: Clone index.html from GitHub
      git:
        repo: https://github.com/sharda-Ekbote/EC2-Ansible-git.git
        dest: /var/www/html
        force: yes
