---
- name: Setup web server on Ubuntu EC2
  hosts: localhost
  become: true
  connection: local
  tasks:
    - name: Install Apache and Git
      apt:
        name:
          - apache2
          - git
        state: present
        update_cache: true

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Clone GitHub repo into /var/www/html without subdir
      git:
        repo: https://github.com/YOUR_USERNAME/EC2-Ansible-git.git
        dest: /var/www/html
        force: yes
        single_branch: yes
        depth: 1

